### ISSUE TITLE
<img src="undefined/blank.gif"

### ISSUE THREAD

**Issue by gcomtoisboudreau** [trinhtam/summernote-emoji#11]
![undefinedEmojis](https://user-images.githubusercontent.com/53087607/63800335-e6f94680-c8db-11e9-8d21-4dd45cfcca9f.png)

this problem is solved after clicking an emoji-menu-tab, but when initialize the emojis are undefined.

**Comment by trinhtam** [comment]
#Relative path to emojis
document.emojiSource = 'tam-emoji/img';

Edit path to folder of emoji images

**Comment by gcomtoisboudreau** [comment]
ya i have done that and it still not working when first click emoji button

**Comment by trinhtam** [comment]
Send me website of you

**Comment by gcomtoisboudreau** [comment]
i would love to but its a private enterprise website =( i can send you code and screenshots

**Comment by trinhtam** [comment]
You check Web inspector > Network. Find path for css, js and image.

**Comment by gcomtoisboudreau** [comment]
css and js files are there, i added emoji in toolbar. The emoji button wont show unless i put the code from the js files directly where the summernote is implemented.

$(InputTextName).summernote({
		height: 200,  
    	lang: sumLang,
    	toolbar: [
            ['insert', ['emoji']],
            ['insert', ['Upload']],
            ['PlusButton', ['Plus']],
            ['TagButton', ['Tag']],
            ['insert', ['link']]
          ],

**Comment by trinhtam** [comment]
<script src="URL_WEBSITE/tam-emoji/js/config.js"></script>
<script src="URL_WEBSITE/tam-emoji/js/tam-emoji.min.js"></script>


document.emojiType = 'image';
document.emojiSource = 'URL_WEBSITE/tam-emoji/img';

**Comment by gcomtoisboudreau** [comment]
tam-emoji.min.js:1 Uncaught TypeError: Cannot read property 'plugins' of undefined
    at tam-emoji.min.js:1
    at tam-emoji.min.js:1
    at tam-emoji.min.js:1

**Comment by trinhtam** [comment]
You try with tam-emoji.js

**Comment by gcomtoisboudreau** [comment]
same error with tam-emoji.js 
with
<script src="URL_WEBSITE/tam-emoji/js/config.js"></script> <script src="URL_WEBSITE/tam-emoji/js/tam-emoji.min.js"></script>
document.emojiType = 'image';
document.emojiSource = 'URL_WEBSITE/tam-emoji/img';

**Comment by gcomtoisboudreau** [comment]
when i put the js code where my summernote is implemented, i have this error:

/undefined/blank.gif:1 GET https://connectdev.bellsolutionstech.ca/undefined/blank.gif 404 (Not Found)
