### ISSUE TITLE
Where is not minified code?

### ISSUE THREAD

**Issue by shchegol** [trinhtam/summernote-emoji#2]
Hello! Where can I look a not-minified code?

**Comment by paul-crashley** [comment]
I second this, any chance of seeing full source code so we can get it working?

**Comment by SaintPaddy** [comment]
Simply copy/paste the code into this website. Then it will generate the non-minified code for you.
https://unminify.com/

**Comment by shchegol** [comment]
The issue is closed. Thanks to the developer!
