### ISSUE TITLE
Not work in IE11

### ISSUE THREAD

**Issue by shchegol** [trinhtam/summernote-emoji#3]
I opened your example in IE11 and unfortunately it not work

**Comment by muelli1000** [comment]
the plugin works fine in chrome and safari. Unfortunately it don't works in firefox. Have you any ideas? thx

**Comment by shchegol** [comment]
Yes I have and I done it with minify file... It cause because all content append in button. IE catch events on button level and don't let it path trough. Simple append content after button, and all will work great. Unfortunately I can't do pull request because minify file.

**Comment by muelli1000** [comment]
Thx. after i append the content after the button, i can choose the emojis in IE and FF.
Do you have change something at the mouseup event to close the layer? In IE and FF the emoji-menu-div is closing after click a link. 
`e(t).hasClass("emoji-picker") ` seems not working. `e(t).html()` returns a empty string if i click on a emoji or a categorie. In Chrome and Safari it works fine.

**Comment by shchegol** [comment]
Try this:
```
t.on("mouseup"), function(i) {
   if($(".emoji-menu").has(i.target).length === 0) {
      n.$panel.hide()
   }
}
```

**Comment by paul-crashley** [comment]
I still cant get this to work on Firefox, have you had any success there?

This is a code snippet:

```
t.on("keydown", function(e) {
                        (e.keyCode === 27 || e.keyCode === 9) && n.$panel.hide()
                    }), t.on("mouseup", function(i) {
                        if($(".emoji-menu").has(i.target).length === 0) {
                            n.$panel.hide()
                        }
                    }), t.on("click", ".emoji-menu-tab", function(i) {
                        i.stopPropagation();
                        var n = 0,
                            t = e(this).attr("class").split(" ");
                        t = t[1].split("-"), 3 !== t.length && (t = t[0] + "-" + t[1], e(".emoji-menu-tabs td").each(function(i) {
                            var o = e(this).find("a"),
                                a = o.attr("class").split(" ");
                            a = a[1].split("-"), a = a[0] + "-" + a[1], t === a ? (o.attr("class", "emoji-menu-tab " + a + "-selected"), n = i) : o.attr("class", "emoji-menu-tab " + a)
                        }), s(n))
                    })
```

**Comment by shchegol** [comment]
The problem is closed. Thanks to @trinhtam
